### ISSUE TITLE
Unexpected Token

### ISSUE THREAD

**Issue by AlexThurston** [vip-git/universal-json-schema#462]
I commented here: https://github.com/vip-git/universal-json-schema/issues/411 but I thought I should create a new issue instead.  

It looks like this is a problem in 3.0.0-rc.5

Also, not using typescript, this is from a clean CRA

```
./node_modules/react-jsonschema-form-material-ui/dist/bundle.js 5834:15
Module parse failed: Unexpected token (5834:15)
File was processed with these loaders:
 * ./node_modules/babel-loader/lib/index.js
You may need an additional loader to handle the result of these loaders.
|   } catch (e) {
|     return { ...t,
>       title: t?.title
|     };
|   }
```

I downgraded to `3.0.0-beta.3` and things seem to be working in that build.

**Comment by vip-git** [comment]
Hi @AlexThurston - There is a setup made for `rc.5`
- https://github.com/vip-git/cra-react-jsonschema-form-material-ui-example

Which seems to be passing. 

Are you able to share your package.json to see what extra dependencies you have that might cause this conflicts ?

Thanks.

**Comment by AlexThurston** [comment]
I pulled down the above code and did 
```
npm install
npm start
```

And get the same error:
```
Failed to compile.

./node_modules/react-jsonschema-form-material-ui/dist/bundle.js 5834:15
Module parse failed: Unexpected token (5834:15)
File was processed with these loaders:
 * ./node_modules/babel-loader/lib/index.js
You may need an additional loader to handle the result of these loaders.
|   } catch (e) {
|     return { ...t,
>       title: t?.title
|     };
|   }
```

I attached my packge-lock.json incase that might be helpful.  I had to tar and gzip it.
[package-lock.tar.gz](https://github.com/vip-git/universal-json-schema/files/8991912/package-lock.tar.gz)

**Comment by vip-git** [comment]
Hi @AlexThurston - I ran this locally on 

Node 14.x and 16.x - with CRA using this setup
- https://github.com/vip-git/cra-react-jsonschema-form-material-ui-example

Its deployed here
- https://cra-react-jsonschema-form-material-ui-example.vercel.app/

Closing this issue for now - incase you end up still having issues - feel free to reopen .

Thanks for mentioning this.

**Comment by AlexThurston** [comment]
I am on OSX, but I also tried on a fresh Ubuntu and got the same error.

**Comment by AlexThurston** [comment]
Same issue encountered when using `yarn`

**Comment by vip-git** [comment]
Hi @AlexThurston - Its resolved now should work in development env as well you can use `3.0.0-rc.6` version.

- https://github.com/vip-git/universal-json-schema/releases/tag/3.0.0-rc.6

Has been update here
- https://github.com/vip-git/cra-react-jsonschema-form-material-ui-example

**Comment by AlexThurston** [comment]
Fantastic, this is working now.  I've got another one for you that I'll raise in a separate issue. :)
